#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : hexedit
Version  : 1.5
Release  : 2
URL      : https://github.com/pixel/hexedit/archive/1.5/hexedit-1.5.tar.gz
Source0  : https://github.com/pixel/hexedit/archive/1.5/hexedit-1.5.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: hexedit-bin = %{version}-%{release}
Requires: hexedit-license = %{version}-%{release}
Requires: hexedit-man = %{version}-%{release}
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(ncurses)

%description
To build from git:
```
./autogen.sh && ./configure && make
```

%package bin
Summary: bin components for the hexedit package.
Group: Binaries
Requires: hexedit-license = %{version}-%{release}

%description bin
bin components for the hexedit package.


%package license
Summary: license components for the hexedit package.
Group: Default

%description license
license components for the hexedit package.


%package man
Summary: man components for the hexedit package.
Group: Default

%description man
man components for the hexedit package.


%prep
%setup -q -n hexedit-1.5
cd %{_builddir}/hexedit-1.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599070990
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%autogen --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1599070990
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/hexedit
cp %{_builddir}/hexedit-1.5/COPYING %{buildroot}/usr/share/package-licenses/hexedit/74a8a6531a42e124df07ab5599aad63870fa0bd4
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/hexedit

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/hexedit/74a8a6531a42e124df07ab5599aad63870fa0bd4

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/hexedit.1
